server:
  port: 8765

spring:
  application:
    name: api-gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    preferIpAddress: true
jwt:
  secret:
    key: ${JWT_SECRET:secretkey}
